### ISSUE TITLE
Making a new Macaque template visible to Template flow

### ISSUE THREAD

**Issue by mtnusf97** [templateflow/templateflow#84]
Hi everybody!
I am trying to use the fMRIPrep pipeline for preprocessing my macaque's data. 
I have made my template (including a probabilistic brain mask, and probabilistic tissue maps) visible to Template flow but I'm still getting some unsolvable errors like this one:
```
FileNotFoundError: No such file or directory '[]' for output 'brain_mask' of a TemplateFlowSelect interface at node name: fmriprep_wf.single_subject_032145_wf.anat_preproc_wf.anat_norm_wf.tf_select
```
Here is an screenshot of my template which can be found at [this site](https://www.nitrc.org/projects/inia19/).

![image](https://user-images.githubusercontent.com/24853605/102123027-9a80a400-3e5b-11eb-814a-cf5dec6734fa.png)

The template has the resolution of 0.5 mm so I named them like this.

And this is the command that I'm sending, based on the documents:
```
fmriprep-docker /home/matin/school/Neuroscience/monkey_test/macaque_data /home/matin/school/Neuroscience/monkey_test/output participant --participant-label 032145 --fs-license-file /home/matin/school/Neuroscience/freesurfer.txt --output-spaces /home/matin/.cache/templateflow/tpl-inia19
```

I am pretty sure that I'm not doing some steps correctly. Could anyone please help me in solving this issue?

**Comment by oesteban** [comment]
Since @bbfrederick showed a functional version of this template working in #7, I wonder whether he could post his version.

I think I had replied (and @mgxd) to this issue somewhere else, could you help us find the duplicate?

Anyways, these are some of the issues that could be the culprit:

- Uncompressed NIfTIs - *fMRIPrep* and other tools may not check for uncompressed files.
- `res-005` - this is an index, so it should start with 1. Also, the zero-padding is not recommended. Please rename to `res-1` all the files (in theory you could remove the `res` entity altogether, but again, some workflows will be hard-wired to check on some resolution entity).
- Nonstandard files: `template_description.json.save` and `tpl-inia19_res-005_NeuroMaps.nii` are nonstandard and likely break pybids' indexing.

**Comment by oesteban** [comment]
Closing for the lack of activity. Please reopen if the problem could not be fixed.
