### ISSUE TITLE
Include species as template metadata field

### ISSUE THREAD

**Issue by rciric** [templateflow/templateflow#86]
Including the species as a metadata field has the potential to improve software integration and enable automation of certain tasks.

* For instance, when the current template-to-template registration workflow is executed, it could automatically create transformation paths only to other templates of the same species.
* Species-specific pipelines could run checks to verify that all target templates are of the appropriate species.
* In general, many operations that query for "all templates" would receive more appropriate results if the query were "all templates of species ___" instead.

I'm not sure if we want to allow only the species itself (i.e., "human", "rat", etc.) or also other more general descriptors/keywords of interest (for instance, "rodent", "primate", etc.)

**Comment by oesteban** [comment]
Now that I think of this, perhaps there's a case to add this species information into BIDS' `dataset_description.json`. Then TemplateFlow would just tag along the general solution of BIDS.

Opinions?

cc/ @effigies @eilidhmacnicol @sappelhoff @franklin-feingold @TheChymera (feel free to attach anyone using BIDS on species other than humans)

**Comment by TheChymera** [comment]
I can write up a PR for this. Also, for preclinical models (particularly the rat and mouse) there exist multiple strains which would also need to be recorded as the templates can look a bit different. For the animal field I would also suggest we use the “genus species” names, yielding:

```
Species : "rattus norvegicus"
Strain : "Wistar"
```

The species syntax, other than being more ambiguous in general, is particualrly relevat for the rats, since most standard strains are R. norvegicus, but if someone were to image a wild rat, it would probably be R. rattus, depending on where the experimenter lives. The species are quite different.

**Comment by eilidhmacnicol** [comment]
I agree using a combination of species and some descriptor (either strain or something more general, maybe akin to `desc`, which could cover genetic modifications versus wild-type) would be best.

However, I wonder if the Latin species syntax is redundant if specifying strain, as strains do not straddle species (i.e., a Wistar rat is only a Rattus norvegicus, and cannot be a Rattus rattus). I guess that its utility would be to filter for lab rats compared to wild rats, but as there hasn't been any work (AFAIK) validating the use of inter-strain resources, it may be limited.

**Comment by oesteban** [comment]
It seems BIDS is going towards accepting the specification of the species in the `participants.tsv` file (which would permit having multi-species datasets, as it is an attribute of the participant). See bids-standard/bids-specification#779.

To specify the species, the issue refers to the [NCBI Taxonomy](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi). So I guess that would sufficiently cover @TheChymera's idea.

Then, I think having the strain as an optional entry may be also useful. WDYT?

**Comment by oesteban** [comment]
One question is whether we want to split genus and specific name, so that it is possible to query something like `get_templates(genus="rattus")` and obtain all the templates corresponding to species of this genus.

I'm not sure this would be easier to implement by having a dict like:

```
  "Genus": "rattus",
  "SpecificName": "norvegicus",
```

But then have sufficient granularity to query species: `get_templates(species="rattus norvegicus")`. The idea being leveraging pybids as much as we can without much rewriting of the indexing if possible.

cc/ @mgxd @effigies

**Comment by oesteban** [comment]
First problems are popping up: https://github.com/templateflow/tpl-VALiDATe29/blob/e9f226f7b4e368a754735e8d8ed4ccaca5fdb42f/template_description.json#L32-L35 has individuals from two species. They virtually have the same brains, and that's argued in the corresponding paper, but we need to handle the situation. For the moment, I made a list for the species field of this particular template.

**Comment by effigies** [comment]
BIDS has put species in a `participants.tsv` column: https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#participants-file

**Comment by oesteban** [comment]
Some templates have a [`template_sample.tsv` file](https://github.com/templateflow/tpl-OASIS30ANTs/blob/7fba99bdf170b3041445d604d3f84914247ce1bc/template_sample.tsv) akin to the `participants.tsv` file. However, it is very strange that the information is preserved (and for the example I gave, we just know the number of animals of each species).

**Comment by eilidhmacnicol** [comment]
I think the solution you've came up with is the best available for that particular situation since I don't know many other instances requiring templates that bridge more than one species. Having said that, unless the source images are also provided, I think knowing which individual comes from which species is not necessary and the number of animals from each species should be sufficient.

In fact, I'd argue that adding strains as a recommended field is of greater importance than knowing individual species, particularly since it isn't recorded in TemplateFlow or BIDS, AFAIK. If a study is looking at strain differences, either between strains (wistar vs sprague-dawley) or "within" strain (wild-types versus knock-outs/ins/downs), and the template is not the same strain as the samples, I don't think it's a given that the two groups would be equidistant from the template.

**Comment by oesteban** [comment]
I'm closing this as all templates now have a "Species" metadata field.

However, two additional issues have been opened to follow-up: #118 regarding the strain based on Eilidh's comment above, and templateflow/python-client#88 to make the inclusion of Species more workable with specific client queries.
